In [ ]:
pip install datarec-lib boto3 torch transformers faiss-cpu

Collecting datarec-lib
  Using cached datarec_lib-1.5.7-py3-none-any.whl.metadata (1.3 kB)
Collecting boto3
  Using cached boto3-1.43.2-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (2.31.0)
Collecting torch
  Using cached torch-2.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting transformers
  Using cached transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Collecting faiss-cpu
  Using cached faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Collecting datarec>=1.5.7 (from datarec-lib)
  Using cached datarec-1.5.7-py3-none-any.whl.metadata (10 kB)
Collecting botocore<1.44.0,>=1.43.2 (from boto3)
  Using cached botocore-1.43.2-py3-none-any.whl.metadata (5.5 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3)
  Using cached s3transfer-0.17.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests) (2023.7.22)
Collecting filelock (from torch)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: setuptools<82 in /opt/conda/lib/python3.11/site-packages (from torch) (68.2.2)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.2)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec>=0.8.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2023.9.2)
Collecting cuda-toolkit==13.0.2 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch)
  Using cached cuda_bindings-13.2.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting nvidia-cudnn-cu13==9.19.0.56 (from torch)
  Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.0 (from torch)
  Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.28.9 (from torch)
  Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.6.0 (from torch)
  Using cached triton-3.6.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.0.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch)
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.13.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.11/site-packages (from transformers) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.11/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.11/site-packages (from transformers) (6.0.1)
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.4.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers)
  Using cached typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.11/site-packages (from transformers) (4.66.1)
Collecting numpy>=1.17 (from transformers)
  Using cached numpy-2.4.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.11/site-packages (from botocore<1.44.0,>=1.43.2->boto3) (2.8.2)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings<14,>=13.0.3->torch)
  Using cached cuda_pathfinder-1.5.4-py3-none-any.whl.metadata (1.9 kB)
Collecting pandas<3,>=2.3 (from datarec>=1.5.7->datarec-lib)
  Using cached pandas-2.3.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting scikit-learn<2,>=1.6 (from datarec>=1.5.7->datarec-lib)
  Using cached scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting gdown<5,>=4.7 (from datarec>=1.5.7->datarec-lib)
  Using cached gdown-4.7.3-py3-none-any.whl.metadata (4.4 kB)
Collecting kagglehub==1.0.0 (from datarec>=1.5.7->datarec-lib)
  Using cached kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting py7zr<1,>=0.22 (from datarec>=1.5.7->datarec-lib)
  Using cached py7zr-0.22.0-py3-none-any.whl.metadata (16 kB)
Collecting platformdirs<5,>=4.4.0 (from datarec>=1.5.7->datarec-lib)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)
Collecting appdirs<2,>=1.4.4 (from datarec>=1.5.7->datarec-lib)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting python-igraph<2,>=1.0 (from datarec>=1.5.7->datarec-lib)
  Using cached python_igraph-1.0.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: PySocks<2,>=1.7 in /opt/conda/lib/python3.11/site-packages (from datarec>=1.5.7->datarec-lib) (1.7.1)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub==1.0.0->datarec>=1.5.7->datarec-lib)
  Using cached kagglesdk-0.1.23-py3-none-any.whl.metadata (13 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.3)
Collecting click>=8.2.1 (from typer->transformers)
  Using cached click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: six in /opt/conda/lib/python3.11/site-packages (from gdown<5,>=4.7->datarec>=1.5.7->datarec-lib) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.11/site-packages (from gdown<5,>=4.7->datarec>=1.5.7->datarec-lib) (4.12.2)
Requirement already satisfied: anyio in /opt/conda/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.0.0)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<3,>=2.3->datarec>=1.5.7->datarec-lib) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas<3,>=2.3->datarec>=1.5.7->datarec-lib) (2023.3)
Collecting texttable (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.16.0 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached pycryptodomex-3.23.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pyzstd>=0.15.9 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached pyzstd-0.19.1-py3-none-any.whl.metadata (2.6 kB)
Collecting pyppmd<1.2.0,>=1.1.0 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached pyppmd-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting pybcj<1.1.0,>=1.0.0 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached pybcj-1.0.7-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.9 kB)
Collecting multivolumefile>=0.2.3 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting inflate64<1.1.0,>=1.0.0 (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached inflate64-1.0.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: brotli>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib) (1.1.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.11/site-packages (from py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib) (5.9.5)
Collecting igraph==1.0.0 (from python-igraph<2,>=1.0->datarec>=1.5.7->datarec-lib)
  Using cached igraph-1.0.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers) (2.16.1)
Requirement already satisfied: scipy>=1.10.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn<2,>=1.6->datarec>=1.5.7->datarec-lib) (1.11.3)
Requirement already satisfied: joblib>=1.3.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn<2,>=1.6->datarec>=1.5.7->datarec-lib) (1.3.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn<2,>=1.6->datarec>=1.5.7->datarec-lib) (3.2.0)
Requirement already satisfied: protobuf in /opt/conda/lib/python3.11/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub==1.0.0->datarec>=1.5.7->datarec-lib) (4.24.3)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting backports-zstd>=1.0.0 (from pyzstd>=0.15.9->py7zr<1,>=0.22->datarec>=1.5.7->datarec-lib)
  Using cached backports_zstd-1.3.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting numpy>=1.17 (from transformers)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.11/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.11/site-packages (from beautifulsoup4->gdown<5,>=4.7->datarec>=1.5.7->datarec-lib) (2.5)
Using cached datarec_lib-1.5.7-py3-none-any.whl (1.9 kB)
Using cached boto3-1.43.2-py3-none-any.whl (140 kB)
Using cached torch-2.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (530.6 MB)
Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl (2.4 kB)
Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl (366.1 MB)
Using cached nvidia_cusparselt_cu13-0.8.0-py3-none-manylinux2014_x86_64.whl (169.9 MB)
Using cached nvidia_nccl_cu13-2.28.9-py3-none-manylinux_2_18_x86_64.whl (196.5 MB)
Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
Using cached triton-3.6.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.2 MB)
Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Using cached transformers-5.7.0-py3-none-any.whl (10.5 MB)
Using cached faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
Using cached botocore-1.43.2-py3-none-any.whl (15.0 MB)
Using cached cuda_bindings-13.2.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.3 MB)
Using cached datarec-1.5.7-py3-none-any.whl (199 kB)
Using cached kagglehub-1.0.0-py3-none-any.whl (70 kB)
Using cached huggingface_hub-1.13.0-py3-none-any.whl (660 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Using cached regex-2026.4.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (799 kB)
Using cached s3transfer-0.17.0-py3-none-any.whl (86 kB)
Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using cached click-8.3.3-py3-none-any.whl (110 kB)
Using cached cuda_pathfinder-1.5.4-py3-none-any.whl (51 kB)
Using cached gdown-4.7.3-py3-none-any.whl (16 kB)
Using cached hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached pandas-2.3.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached py7zr-0.22.0-py3-none-any.whl (67 kB)
Using cached python_igraph-1.0.0-py3-none-any.whl (9.2 kB)
Using cached igraph-1.0.0-cp39-abi3-manylinux_2_28_x86_64.whl (5.7 MB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached inflate64-1.0.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (99 kB)
Using cached kagglesdk-0.1.23-py3-none-any.whl (217 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Using cached pybcj-1.0.7-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (50 kB)
Using cached pycryptodomex-3.23.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Using cached pyppmd-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached pyzstd-0.19.1-py3-none-any.whl (23 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Using cached texttable-1.7.0-py2.py3-none-any.whl (10 kB)

In [ ]:
from datarec.datasets import Movielens
from io import BytesIO
import boto3
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel
import faiss

In [ ]:
s3 = boto3.client(
        "s3",
        aws_access_key_id="",
        aws_secret_access_key="",
        aws_session_token="",
        region_name="us-east-1"
    )
BUCKET = "rosu-de300spring2026-bucket"

In [4]:
def load_data():
    RATINGS = "datasets/ratings.csv"
    USERS = "datasets/users.dat"
    MOVIES = "datasets/movies.dat"

    users_df = ""
    movies_df = ""
    ratings_df = ""
    
    try:
        # Get users data
        response = s3.get_object(Bucket=BUCKET, Key=USERS)
        print("Users data exists in S3 bucket")
        print("Retrieving users data from S3 bucket")
        users_df = pd.read_csv(BytesIO(response["Body"].read()), sep="::", engine="python", encoding="latin-1", header=None, names=["user_id", "gender", "age", "occupation", "zip_code"])
    
        # Get movies data
        response = s3.get_object(Bucket=BUCKET, Key=MOVIES)
        print("Movies data exists in S3 bucket")
        print("Retrieving movies data from S3 bucket")
        movies_df = pd.read_csv(BytesIO(response["Body"].read()), sep="::", engine="python", encoding="latin-1", header=None, names=["item_id", "title", "genres"])
        
        # Get ratings data
        response = s3.get_object(Bucket=BUCKET, Key=RATINGS)
        print("Ratings data exists in S3 bucket")
        print("Retrieving ratings data from S3 bucket")
        ratings_df = pd.read_csv(response["Body"])
        
        return users_df, movies_df, ratings_df
    except:
        print("Some data not found in S3 bucket")
        dataset = Movielens(version='1m').prepare_and_load()
        ratings_df = dataset.data
        ratings_df.to_csv("ratings.csv", index=False)
        print("Uploading ratings data to S3 bucket")
        s3.upload_file("ratings.csv", BUCKET, "datasets/ratings.csv")
        
        return users_df, movies_df, ratings_df

In [5]:
def add_year_column(movies_df):
    movies_df["year"] = movies_df["title"].str.extract(r"\((\d{4})\)").astype("Int64")
    return movies_df

In [6]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_NAME = "distilbert-base-uncased"  # for illustration, 66M model

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
encoder = AutoModel.from_pretrained(MODEL_NAME).to(DEVICE)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [7]:
# BERT encode helper
@torch.no_grad()
def bert_embed(texts, max_len=32):
    batch = tokenizer(
        texts, padding=True, truncation=True, max_length=max_len, return_tensors="pt"
    )
    batch = {k: v.to(DEVICE) for k, v in batch.items()}
    out = encoder(**batch)
    cls = out.last_hidden_state[:, 0]          # first column [CLS]-like token for classification
    emb = F.normalize(cls, dim=-1)             # normalization
    return emb.cpu().numpy().astype("float32") # size (B, 768)

In [8]:
# batch size BERT encode helper
@torch.no_grad()
def bert_embed(texts, max_len=32, batch_size=4):
    all_embs = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]
        batch = tokenizer(
            batch_texts, padding=True, truncation=True, max_length=max_len, return_tensors="pt"
        )
        batch = {k: v.to(DEVICE) for k, v in batch.items()}
        out = encoder(**batch)
        cls = out.last_hidden_state[:, 0]
        emb = F.normalize(cls, dim=-1)
        all_embs.append(emb.cpu().numpy().astype("float32"))

        del batch, out, cls, emb

        if DEVICE == "cuda":
            torch.cuda.empty_cache()

    return np.vstack(all_embs)

In [9]:
# Create movie embeddings
def create_embeddings(df, year=2026):
    movies = df[df["year"] <= year].copy()
    movie_id_list = movies["item_id"].tolist()
    movies["text"] = movies["title"] + ". " + movies["genres"]

    # Check if index file exists in S3
    try:
        response = s3.get_object(Bucket=BUCKET, Key=f"embeddings-{year}.index")
        with open("temp.index", "wb") as f:
            f.write(response["Body"].read())
        index = faiss.read_index("temp.index")
        print("Embeddings exist in S3")

    except:
        print("Embeddings don't exist in S3")
        
        movie_vecs = bert_embed(movies["text"].tolist())
        
        index = faiss.IndexFlatIP(movie_vecs.shape[1])
        index.add(movie_vecs)

        print("Uploading embedding index file to S3")
        faiss.write_index(index, "embeddings.index")
        s3.upload_file("embeddings.index", BUCKET, f"embeddings-{year}.index")
    
    return movies, movie_id_list, index

In [10]:
# Pick a cold user and a top 5% user
def pick_users(users_df, ratings_df):
    cold_user_id = max(set(users_df["user_id"].unique())) + 1

    user_counts = ratings_df.groupby("user_id").size()
    threshold = np.percentile(user_counts, 95)
    top_users = user_counts[user_counts >= threshold].index.tolist()
    top_user_id = np.random.choice(top_users)
        
    return cold_user_id, top_user_id

In [11]:
# Build user text from last N ratings
def build_user_text(user_id, ratings, movies, N=10):
    valid_movie_ids = set(movies["item_id"]) # since movies was filtered by year earlier in pipeline
    hist = (ratings[(ratings["user_id"] == user_id) & (ratings["rating"] >= 4) & (ratings["item_id"].isin(valid_movie_ids))].sort_values("timestamp").tail(N)["item_id"].tolist())
    if not hist:
        return "no history", set()
    text = movies.set_index("item_id").loc[hist, "text"].tolist()
    return " ".join(text), set(hist)

In [12]:
# Output recommendation and store file with summary on S3
def recommend_and_store(user_id, user_type, max_year, ratings, movies, movie_id_list, k=3, N=10):
    user_text, seen = build_user_text(user_id, ratings, movies, N)
    u = bert_embed([user_text])  # (1, 768)
    scores, idx = index.search(u, k + len(seen))  # keep track of what was seen by the user
    recs = []
    
    for j in idx[0]:
        iid = movie_id_list[j]
        if iid not in seen:
            recs.append(iid)
        if len(recs) == k:
            break
            
    recommended_movies = (movies[movies["item_id"].isin(recs)][["item_id", "title", "genres"]].to_dict("records"))

    user_ratings = ratings[ratings["user_id"] == user_id]

    if len(user_ratings) > 0:
        last_interaction_time = user_ratings["timestamp"].max()
        total_ratings = len(user_ratings)
        avg_rating = user_ratings["rating"].mean()
        liked_movies = len(user_ratings[user_ratings["rating"] >= 4])
    else:
        last_interaction_time = None
        total_ratings = 0
        avg_rating = None
        liked_movies = 0

    output = pd.DataFrame([{
        "User_ID": user_id,
        "User_Type": user_type,
        "Last_Interaction_Time": last_interaction_time,
        "Total_Ratings": total_ratings,
        "Average_Rating": avg_rating,
        "Liked_Movies_Rated_4_or_Higher": liked_movies,
        "Recommendation Max Year": max_year,
        "Recommended_Movies": recommended_movies
    }])

    local_file = f"recommendations_user-{user_id}.csv"
    output.to_csv(local_file, index=False)

    s3.upload_file(local_file, BUCKET, f"recommendations/{local_file}")

    return output

In [11]:
# Execution pipeline for movies up to 1980

In [12]:
(users_df, movies_df, ratings_df) = load_data()
# print(type(users_df))
print(users_df.columns)
# print(users_df.head(5))
# print(type(movies_df))
print(movies_df.columns)
# print(type(ratings_df))
print(ratings_df.columns)

Users data exists in S3 bucket
Retrieving users data from S3 bucket
Movies data exists in S3 bucket
Retrieving movies data from S3 bucket
Ratings data exists in S3 bucket
Retrieving ratings data from S3 bucket
Index(['user_id', 'gender', 'age', 'occupation', 'zip_code'], dtype='object')
Index(['item_id', 'title', 'genres'], dtype='object')
Index(['user_id', 'item_id', 'rating', 'timestamp'], dtype='object')

In [13]:
movies_df = add_year_column(movies_df)
print(movies_df.columns)

Index(['item_id', 'title', 'genres', 'year'], dtype='object')

In [15]:
max_year = 1980
(movies_df, movie_id_list, index) = create_embeddings(movies_df, max_year)

Embeddings don't exist in S3
Uploading embedding index file to S3

In [16]:
(cold_user_id, top_user_id) = pick_users(users_df, ratings_df)
print(f"Cold user id: {cold_user_id} \nTop user id: {top_user_id}")
# ratings_df.loc[ratings_df["user_id"] == top_user_id]

Cold user id: 6041
Top user id: 731

In [17]:
recommend_and_store(cold_user_id, "Cold User", max_year, ratings_df, movies_df, movie_id_list, k=5, N=10)

,User_ID,User_Type,Last_Interaction_Time,Total_Ratings,Average_Rating,Liked_Movies_Rated_4_or_Higher,Recommendation Max Year,Recommended_Movies
0,6041,Cold User,None,0,None,0,1980,"[{'item_id': 2150, 'title': 'Gods Must Be Craz..."

In [19]:
recommend_and_store(top_user_id, "Top User", max_year, ratings_df, movies_df, movie_id_list, k=5, N=10)

,User_ID,User_Type,Last_Interaction_Time,Total_Ratings,Average_Rating,Liked_Movies_Rated_4_or_Higher,Recommendation Max Year,Recommended_Movies
0,731,Top User,975531200,642,3.778816,392,1980,"[{'item_id': 1030, 'title': 'Pete's Dragon (19..."

In [20]:
# Execution pipeline for all movies

In [16]:
(users_df, movies_df, ratings_df) = load_data()

Users data exists in S3 bucket
Retrieving users data from S3 bucket
Movies data exists in S3 bucket
Retrieving movies data from S3 bucket
Ratings data exists in S3 bucket
Retrieving ratings data from S3 bucket

In [17]:
movies_df = add_year_column(movies_df)

In [19]:
max_year = 2026
(movies_df, movie_id_list, index) = create_embeddings(movies_df, max_year)

Embeddings don't exist in S3
Uploading embedding index file to S3

In [20]:
(cold_user_id, top_user_id) = pick_users(users_df, ratings_df)

In [21]:
recommend_and_store(cold_user_id, "Cold User", max_year, ratings_df, movies_df, movie_id_list, k=5, N=10)

,User_ID,User_Type,Last_Interaction_Time,Total_Ratings,Average_Rating,Liked_Movies_Rated_4_or_Higher,Recommendation Max Year,Recommended_Movies
0,6041,Cold User,None,0,None,0,2026,"[{'item_id': 192, 'title': 'Show, The (1995)',..."

In [22]:
recommend_and_store(top_user_id, "Top User", max_year, ratings_df, movies_df, movie_id_list, k=5, N=10)

,User_ID,User_Type,Last_Interaction_Time,Total_Ratings,Average_Rating,Liked_Movies_Rated_4_or_Higher,Recommendation Max Year,Recommended_Movies
0,148,Top User,980194240,624,3.733974,391,2026,"[{'item_id': 1460, 'title': 'That Darn Cat! (1..."

In [ ]:
# My user profile execution pipline

In [13]:
(users_df, movies_df, ratings_df) = load_data()

Users data exists in S3 bucket
Retrieving users data from S3 bucket
Movies data exists in S3 bucket
Retrieving movies data from S3 bucket
Ratings data exists in S3 bucket
Retrieving ratings data from S3 bucket

In [14]:
movies_df = add_year_column(movies_df)

In [15]:
max_year = 2026
(movies_df, movie_id_list, index) = create_embeddings(movies_df, max_year)

Embeddings exist in S3

In [20]:
try:
    response = s3.get_object(Bucket=BUCKET, Key="profiles/my-profile.csv")
    print("My profile exists in S3 bucket")
    print("Retrieving my profile from S3 bucket...")
    my_ratings_df = pd.read_csv(response["Body"])
    
except:
    my_user_id = 7777
    my_ratings_df = pd.DataFrame([
        {"user_id": my_user_id, "item_id": 1365, "rating": 5, "timestamp": 1},
        {"user_id": my_user_id, "item_id": 2706, "rating": 4, "timestamp": 2},
        {"user_id": my_user_id, "item_id": 3667, "rating": 3, "timestamp": 3},
        {"user_id": my_user_id, "item_id": 3684, "rating": 4, "timestamp": 4},
        {"user_id": my_user_id, "item_id": 1881, "rating": 2, "timestamp": 5},
        {"user_id": my_user_id, "item_id": 2224, "rating": 5, "timestamp": 6},
        {"user_id": my_user_id, "item_id": 730, "rating": 4, "timestamp": 7},
        {"user_id": my_user_id, "item_id": 355, "rating": 3, "timestamp": 8},
        {"user_id": my_user_id, "item_id": 1241, "rating": 2, "timestamp": 9},
        {"user_id": my_user_id, "item_id": 326, "rating": 5, "timestamp": 10}
    ])
    my_ratings_df.to_csv("my-profile.csv", index=False)
    print("Uploading my profile to S3...")
    s3.upload_file("my-profile.csv", BUCKET, "profiles/my-profile.csv")

My profile exists in S3 bucket
Retrieving my profile from S3 bucket...

In [21]:
recommend_and_store(my_ratings_df["user_id"][0], "My Profile", max_year, my_ratings_df, movies_df, movie_id_list, k=5, N=10)

,User_ID,User_Type,Last_Interaction_Time,Total_Ratings,Average_Rating,Liked_Movies_Rated_4_or_Higher,Recommendation Max Year,Recommended_Movies
0,7777,My Profile,10,10,3.7,6,2026,"[{'item_id': 1010, 'title': 'Love Bug, The (19..."